"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: "rtl" | "ltr"
  isLoaded: boolean
}

const translations = {
  ar: {
    // Auth
    login: "تسجيل الدخول",
    "login.title": "تسجيل الدخول إلى حسابك",
    "login.description": "أدخل بريدك الإلكتروني وكلمة المرور للوصول إلى لوحة التحكم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    "forgot.password": "نسيت كلمة المرور؟",
    "forgot.password.title": "نسيت كلمة المرور؟",
    "forgot.password.description": "أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور",
    "send.reset.link": "إرسال رابط إعادة التعيين",
    "back.to.login": "العودة إلى تسجيل الدخول",
    "check.email": "تحقق من بريدك الإلكتروني",
    "check.email.description": "لقد أرسلنا لك رابط إعادة تعيين كلمة المرور. يرجى التحقق من بريدك الإلكتروني.",
    "welcome.back": "مرحباً بك مجدداً",
    "enter.credentials": "أدخل بياناتك للوصول إلى لوحة التحكم",
    "reset.password": "إعادة تعيين كلمة المرور",
    "reset.password.description": "أدخل كلمة المرور الجديدة لحسابك",

    // Dashboard
    dashboard: "لوحة التحكم",
    "news.management": "إدارة الأخبار",
    "events.management": "إدارة الفعاليات",
    "members.management": "إدارة الأعضاء",
    "user.management": "إدارة المستخدمين",
    profile: "الملف الشخصي",
    "phoneNumber":"رقم الهاتف",

    logout: "تسجيل الخروج",
    "switch.language": "تبديل اللغة",
    "add.member": "إضافة عضو",
    "system.settings": "إعدادات النظام",
    "dashboard.title": "لوحة التحكم | إدارة الرياضة",
    "dashboard.description": "نظرة عامة على لوحة تحكم إدارة الرياضة",
    "news.title": "إدارة الأخبار | إدارة الرياضة",
    "news.description": "إدارة المقالات الإخبارية للموقع الرياضي",
    "events.title": "إدارة الفعاليات | إدارة الرياضة",
    "events.description": "إدارة الفعاليات للموقع الرياضي",
    "users.title": "إدارة المستخدمين | إدارة الرياضة",
    "users.description": "إدارة مستخدمي النظام",
    "settings.title": "الإعدادات | إدارة الرياضة",
    "settings.description": "إعدادات النظام",
    "create.event.title": "إنشاء فعالية | إدارة الرياضة",
    "create.event.description": "إنشاء فعالية جديدة",
    "edit.event.title": "تعديل فعالية | إدارة الرياضة",
    "edit.event.description": "تعديل فعالية موجودة",
    "create.user.title": "إنشاء مستخدم | إدارة الرياضة",
    "create.user.description": "إنشاء مستخدم جديد",

    // Stats
    "total.news": "إجمالي الأخبار",
    "upcoming.events": "الفعاليات القادمة",
    "past.events": "الفعاليات السابقة",
    "active.users": "المستخدمين النشطين",
    "from.last.month": "من الشهر الماضي",
    "scheduled.this.week": "مجدولة هذا الأسبوع",
    "from.last.quarter": "من الربع الماضي",
    "since.last.login": "منذ آخر تسجيل دخول",
    members: "الاعضاء",
    "member.profile": "الملف الشخصي",
    // "confirm.delete.user.title":"حذف المستخدم",
    // "confirm.delete.user.description":"هل أنت متأكد من رغبتك في حذف   ذا المستخدم؟",
    // "confirm.delete.user.button":"حذف",
    // "confirm.delete.user.cancel":"إلغاء",
    "confirm.delete.member.title":"حذف العضو",
    "confirm.delete.member.description":"هل أنت متأكد من رغبتك في حذف هذا العضو؟",
    "confirm.delete.member.button":"حذف",
    "confirm.delete.member.cancel":"إلغاء",
    "other.language": "اللغة الأخرى",
    "member.not.found": "عضو غير موجود",
    "back.to.members": "العودة إلى قائمة الأعضاء",
    "edit.member": "تعديل العضو",
    "description": "الوصف",
    "position": "الموقع",
    "Image":"الصورة",
    "name.ar":"الأسم بالعربي",
    "name.en":"الأسم بالنجليزي",
    "position.ar":"المنصب بالعربي",
    "position.en":"المنصب بالانجليزي",
    "member.image":"ارفق صوره",
    "create.member":" أضف عضو",
    "drag.or.upload":"  اسحب او ارفع صوره ",
    "supported.formats":"يدعم صيغ الصور المختلفه",

    // Content
    "content.overview": "نظرة عامة على المحتوى",
    "recent.news": "أحدث الأخبار",
    "recent.news.description": "آخر المقالات الإخبارية المنشورة",
    "upcoming.events.title": "الفعاليات القادمة",
    "upcoming.events.description": "الفعاليات المجدولة للثلاثين يومًا القادمة",

    // News
    "add.news": "إضافة خبر",
    "create.news": "إنشاء خبر جديد",
    "edit.news": "تعديل الخبر",
    "news.title.ar": "العنوان (بالعربية)",
    "news.title.en": "العنوان (بالإنجليزية)",
    "news.title.ar.placeholder": "أدخل عنوان الخبر بالعربية",
    "news.title.en.placeholder": "أدخل عنوان الخبر بالإنجليزية",
    "news.content.ar": "المحتوى (بالعربية)",
    "news.content.en": "المحتوى (بالإنجليزية)",
    "news.content.ar.placeholder": "أدخل محتوى الخبر بالعربية",
    "news.content.en.placeholder": "أدخل محتوى الخبر بالإنجليزية",
    "confirm.delete.news.title":"حذف الخبر",
    "confirm.delete.news.description":"هل أنت متأكد من رغبتك في حذف هذا الخبر؟",
    "confirm.delete.news.button":"حذف",
    "confirm.delete.news.cancel":"إلغاء",

    content: "المحتوى",
    "publication.date": "تاريخ النشر",
    "select.date": "اختر التاريخ",
    image: "الصورة",
    "news.images": "صور الخبر (الحد الأقصى 3 صور)",
    "upload.image": "رفع صورة",
    "add.image": "إضافة صورة",
    "images.added": "صورة مضافة",
    "choose.image": "اختر صورة",
    "change.image": "تغيير الصورة",
    "no.image.uploaded": "لم يتم رفع صورة",
    "image.required": "يجب إضافة صورة واحدة على الأقل",
    "update.news": "تحديث الخبر",
    "update.news.success.title": "تم تحديث الخبر",
    "update.news.success.description": "تم تحديث الخبر بنجاح.",
    "create.news.success.title": "تم إنشاء الخبر",
    "create.news.success.description": "تم إنشاء الخبر بنجاح.",
    "news.save.error": "حدث خطأ أثناء حفظ الخبر",
    "news.category.placeholder": "اختر فئة الخبر",
    "loading.categories": "جاري تحميل الفئات...",
    "no.categories.available": "لا توجد فئات متاحة",
    "create.news.button": "إنشاء خبر جديد",
    "news.category": "تصنيف الخبر",
    "news.featured": "مميز",
    "news.language": "اللغة",
    "news.publish": "نشر",
    "news.unpublish": "إلغاء النشر",
    "news.delete": "حذف",
    "news.view": "عرض",
    "news.management.title": "إدارة الأخبار",
    "news.delete.success": "تم حذف المقال الإخباري بنجاح.",
    "news.delete.error": "فشل حذف المقال الإخباري. يرجى المحاولة مرة أخرى.",
    "open.menu": "فتح القائمة",
    "edit.news.title": "تعديل خبر | إدارة الرياضة",
    "edit.news.description": "تعديل مقال إخباري موجود",
    "news.not.found": "لم يتم العثور على المقال الإخباري",
    "news.not.found.error": "لم يتم العثور على المقال الإخباري. قد يكون تم حذفه أو تحريكه.",
    "news.per.page":"عدد الأخبار",
    
    // Events
    "add.event": "إضافة فعالية",
    "create.event": "إنشاء فعالية جديدة",
    "edit.event": "تعديل الفعالية",
    "event.title": "عنوان الفعالية",
    "event.date": "تاريخ الفعالية",
    "event.time": "وقت الفعالية",
    "event.type": "نوع الفعالية",
    "event.category": "تصنيف الفعالية",
    "event.featured": "مميز",
    "event.language": "اللغة",
    "event.preview": "معاينة",
    "event.publish": "نشر",
    "event.unpublish": "إلغاء النشر",
    "event.delete": "حذف",
    "event.view": "عرض",
    "event.location": "الموقع",
    location: "الموقع",
    upcoming: "قادمة",
    past: "سابقة",
    "update.event": "تحديث الفعالية",
    "create.event.button": "إنشاء الفعالية",
    "events.management.title": "إدارة الفعاليات",
    "event.save.draft": "حفظ كمسودة",
    tournament: "بطولة",
    championship: "دوري",
    seminar: "ندوة",
    training: "تدريب",
    exhibition: "معرض",
    conference: "مؤتمر",
    other: "أخرى",

    // Users
    users: "المستخدمين",
    "add.user": "إضافة مستخدم",
    "create.user": "إنشاء مستخدم جديد",
    "edit.user": "تعديل المستخدم",
    name: "الاسم",
    role: "الدور",
    status: "الحالة",
    admin: "مدير",
    editor: "محرر",
    viewer: "مشاهد",
    active: "نشط",
    inactive: "غير نشط",
    "update.user": "تحديث المستخدم",
    "create.user.button": "إنشاء المستخدم",
    "user.management.title": "إدارة المستخدمين",
    "user.delete.success.title": "تم حذف المستخدم",
    "user.delete.success.description": "تم حذف المستخدم بنجاح.",
    "user.delete.error": "حدث خطأ أثناء حذف المستخدم. يرجى المحاولة مرة أخرى.",
    "user.fetch.error": "حدث خطأ أثناء جلب بيانات المستخدم. يرجى المحاولة مرة أخرى.",
    "users.load.error": "فشل في تحميل المستخدمين. يرجى المحاولة مرة أخرى لاحقًا.",
    "user.not.found": "لم يتم العثور على المستخدم",
    "user.not.found.error": "لم يتم العثور على المستخدم. قد يكون تم حذفه أو تحريكه.",
    "phone.number": "رقم الهاتف",
    "confirm.delete.user.title":"حذف المستخدم",
    "confirm.delete.user.description":"هل أنت متأكد من رغبتك في حذف هذا المستخدم؟",
    "confirm.delete.user.button":"حذف",
    "confirm.delete.user.cancel":"إلغاء",
    user: "المستخدم",
    "profile.image": "الصورة الشخصية",

    // Table
    actions: "الإجراءات",
    edit: "تعديل",
    delete: "حذف",
    previous: "السابق",
    next: "التالي",
    "no.news.found": "لم يتم العثور على أخبار",
    "no.events.found": "لم يتم العثور على فعاليات",
    "no.users.found": "لم يتم العثور على مستخدمين",
    "current.user": "المستخدم الحالي",

    // Profile
    "personal.information": "المعلومات الشخصية",
    "update.profile": "تحديث الملف الشخصي",
    "change.password": "تغيير كلمة المرور",
    "current.password": "كلمة المرور الحالية",
    "new.password": "كلمة المرور الجديدة",
    "confirm.password": "تأكيد كلمة المرور",
    "profile.picture": "الصورة الشخصية",
    "profile.not.found": "لم يتم العثور على الملف الشخصي",
    "profile.data.error": "حدث خطأ أثناء جلب بيانات الملف الشخصي",

    // Settings
    "general.settings": "الإعدادات العامة",
    language: "اللغة",
    arabic: "العربية",
    english: "الإنجليزية",
    notifications: "الإشعارات",
    "notifications.description": "إدارة إعدادات الإشعارات الخاصة بك",
    "email.notifications": "إشعارات البريد الإلكتروني",
    "email.notifications.description": "تلقي إشعارات عبر البريد الإلكتروني عند إضافة محتوى جديد أو تحديثه.",
    "push.notifications": "الإشعارات الفورية",
    "push.notifications.description": "تلقي إشعارات فورية عند إضافة محتوى جديد أو تحديثه.",

    // Months
    jan: "يناير",
    feb: "فبراير",
    mar: "مارس",
    apr: "أبريل",
    may: "مايو",
    jun: "يونيو",
    jul: "يوليو",
    aug: "أغسطس",
    sep: "سبتمبر",
    oct: "أكتوبر",
    nov: "نوفمبر",
    dec: "ديسمبر",

    // Footer
    copyright: "© {year} إدارة الرياضة. جميع الحقوق محفوظة.",
    
    // Platform
    "platform.description": "منصة متكاملة لإدارة الأنشطة الرياضية والفعاليات بكفاءة عالية",
    "platform.features": "مميزات النظام",
    "platform.easy.management": "إدارة سهلة",
    "platform.easy.management.description": "واجهة سهلة الاستخدام لإدارة جميع الأنشطة والفعاليات الرياضية",
    "platform.secure": "آمن وموثوق",
    "platform.secure.description": "حماية كاملة للبيانات والمعلومات الخاصة بك مع تشفير متقدم",
    "platform.analytics": "تحليلات متقدمة",
    "platform.analytics.description": "رؤى وتحليلات شاملة لمساعدتك على اتخاذ قرارات أفضل",

    // Misc
    by: "بواسطة",
    on: "في",
    "pick.a.date": "اختر تاريخًا",
    "select.event.type": "اختر نوع الفعالية",
    "enter.event.location": "أدخل موقع الفعالية",
    "select.option": "اختر خيارًا",
    "search.placeholder": "بحث...",
    "filter.by": "تصفية حسب",
    "sort.by": "ترتيب حسب",
    "items.per.page": "عناصر في الصفحة",
    showing: "عرض",
    of: "من",
    items: "عناصر",
    page: "صفحة",
    "first.page": "الصفحة الأولى",
    "last.page": "الصفحة الأخيرة",
    "go.to.page": "انتقل إلى الصفحة",
    "no.results": "لا توجد نتائج",
    error: "خطأ",
    success: "نجاح",
    warning: "تحذير",
    info: "معلومات",
    confirm: "تأكيد",
    close: "إغلاق",
    save: "حفظ",
    add: "إضافة",
    remove: "إزالة",
    view: "عرض",
    download: "تنزيل",
    upload: "رفع",
    copy: "نسخ",
    paste: "لصق",
    cut: "قص",
    undo: "تراجع",
    redo: "إعادة",
    "select.all": "تحديد الكل",
    "select.none": "إلغاء التحديد",
    select: "تحديد",
    clear: "مسح",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب",
    refresh: "تحديث",
    more: "المزيد",
    less: "أقل",
    "show.more": "عرض المزيد",
    "show.less": "عرض أقل",
    expand: "توسيع",
    collapse: "طي",
    details: "تفاصيل",
    summary: "ملخص",

    // UI Common
    cancel: "إلغاء",
    saving: "جاري الحفظ...",
    sending: "جاري الإرسال...",
    "logging.in": "جاري تسجيل الدخول...",
    required: "مطلوب",
    optional: "اختياري",
    preview: "معاينة",

    // User form validation errors
    "name.min.length.error": "يجب أن يكون الاسم 3 أحرف على الأقل.",
    "email.invalid.error": "يرجى إدخال عنوان بريد إلكتروني صالح.",
    "phone.number.invalid.error": "يرجى إدخال رقم هاتف صالح.",
    "role.required.error": "يرجى اختيار دور.",
    "status.required.error": "يرجى اختيار حالة.",
    "password.min.length.error": "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
    "passwords.not.matching.error": "كلمات المرور غير متطابقة.",
    
    // News form validation errors
    "title.ar.min.length.error": "يجب أن يكون العنوان 3 أحرف على الأقل.",
    "title.en.min.length.error": "يجب أن يكون العنوان 3 أحرف على الأقل.",
    "content.ar.min.length.error": "يجب أن يكون المحتوى 10 أحرف على الأقل.",
    "content.en.min.length.error": "يجب أن يكون المحتوى بالإنجليزية 10 أحرف على الأقل.",
    "category.is.required":"يجب اختيار نوع الخبر",

    // Toast notifications
    "please.wait": "يرجى الانتظار...",
    "operation.success": "تمت العملية بنجاح",
    "operation.failed": "فشلت العملية",
    "login.success": "تم تسجيل الدخول بنجاح",
    "welcome.message": "مرحبًا بك في لوحة تحكم إدارة الرياضة",
    // "login.failed": "فشل تسجيل الدخول",
    // "password.incorrect": "كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى",
    "login.error.message": "حدث خطأ أثناء تسجيل الدخول",
    "email.not.found": "البريد الإلكتروني غير مسجل في النظام",
    "your.account.is.not.active" :"هذا الحساب غير مفعل",
    "connection.error": "خطأ في الاتصال",
    "image.deleted.success": "تم حذف الصورة بنجاح",
    "server.connection.error": "حدث خطأ أثناء محاولة الاتصال بالخادم",
    "saving.settings": "جاري حفظ الإعدادات",
    "settings.saved": "تم حفظ الإعدادات",
    "settings.saved.description": "تم حفظ إعدادات لوحة التحكم بنجاح",
    "changing.password": "جاري تغيير كلمة المرور",
    "password.changed": "تم تغيير كلمة المرور",
    "password.changed.description": "تم تغيير كلمة المرور بنجاح",
    "resetting.password": "جاري إعادة تعيين كلمة المرور",
    "password.reset.success": "تم إعادة تعيين كلمة المرور",
    "password.reset.error": "خطأ في إعادة التعيين",
    "password.reset.failed": "فشل إعادة تعيين كلمة المرور",
    "updating.user": "جاري تحديث المستخدم",
    "creating.user": "جاري إنشاء مستخدم جديد",
    "user.updated.title": "تم تحديث المستخدم",
    "user.updated.description": "تم تحديث بيانات المستخدم بنجاح",
    "user.created.title": "تم إنشاء المستخدم",
    "user.created.description": "تم إنشاء المستخدم الجديد بنجاح",
    "unauthorized.title": "غير مصرح",
    "unauthorized.description": "ليس لديك الصلاحية للوصول إلى هذه الصفحة",
    "login.email.not.found": "البريد الإلكتروني غير مسجل في النظام",
    "login.password.incorrect": "كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى",
    "user.save.error.title": "خطأ",
    "user.save.error.description": "حدث خطأ أثناء حفظ المستخدم",
    "event.deleted": "تم حذف الفعالية",
    "event.deleted.description": "تم حذف الفعالية بنجاح",
    "member.deleted": "تم حذف العضو",
  
    "member.deleted.description": "تم حذف العضو بنجاح",
    "member.delete.error": "فشل حذف العضو. يرجى المحاولة مرة أخرى",
    "profile.view.error": "فشل عرض الملف الشخصي. يرجى المحاولة مرة أخرى",
    "file.type.invalid": "نوع الملف غير صالح. يرجى اختيار صورة",
    "file.size.too.large": "حجم الملف كبير جدًا",
    "file.size.limit.message": "يجب ألا يتجاوز حجم الملف {size}",
    "max.images.limit": "لا يمكن إضافة أكثر من {0} صور",
    "image.delete.error": "حدث خطأ أثناء حذف الصورة",
    "user.delete.error.title": "فشل حذف المستخدم",
    "user.delete.error.description": "فشل حذف المستخدم. يرجى المحاولة مرة أخرى",

    // Form validations - Arabic
    "verification.code.min.length.error": "يجب أن يكون رمز التحقق 6 أرقام على الأقل.",
    "current.password.min.length.error": "يجب أن تكون كلمة المرور الحالية 8 أحرف على الأقل.",
    "new.password.min.length.error": "يجب أن تكون كلمة المرور الجديدة 8 أحرف على الأقل.",
    "date.required": "التاريخ مطلوب.",
    "time.required": "الوقت مطلوب.",
    "location.ar.min.length.error": "يجب أن يكون الموقع بالعربية 5 أحرف على الأقل.",
    "location.en.min.length.error": "يجب أن يكون الموقع بالإنجليزية 5 أحرف على الأقل.",
    "category.required": "يرجى اختيار تصنيف.",
    "unauthorized.error": "غير مصرح لك بتنفيذ هذة العملية",
    "this.month": "هذا الشهر",
    "latest.news": "أحدث الأخبار شهرياً",
    "news.increase": "زيادة في الأخبار",
    "news.decrease": "انخفاض في الأخبار",
    "no.change": "لا يوجد تغيير"
  },
  en: {
    // Auth
    login: "Login",
    "login.title": "Login to your account",
    "login.description": "Enter your email and password to access the dashboard",
    email: "Email",
    password: "Password",
    "forgot.password": "Forgot your password?",
    "forgot.password.title": "Forgot your password?",
    "forgot.password.description": "Enter your email address and we'll send you a link to reset your password",
    "send.reset.link": "Send Reset Link",
    "back.to.login": "Back to login",
    "check.email": "Check your email",
    "check.email.description": "We've sent you a password reset link. Please check your email.",
    "welcome.back": "Welcome back",
    "enter.credentials": "Enter your credentials to access the dashboard",
    "reset.password": "Reset Password",
    "reset.password.description": "Enter a new password for your account",
    "latest.news": "Latest News Monthly",
    // Dashboard
    dashboard: "Dashboard",
    "news.management": "News Management",
    "events.management": "Events Management",
    "members.management": "Members Management",
    "user.management": "User Management",
    profile: "Profile",
    logout: "Log out",
    "phoneNumber" : "phone number",
    "switch.language": "Switch Language",
    "add.member": "Add Member",
    "system.settings": "System Settings",
    "dashboard.title": "Dashboard | Sports Management",
    "dashboard.description": "Overview of the sports management dashboard",
    "news.title": "News Management | Sports Management",
    "news.description": "Manage news articles for the sports website",
    "events.title": "Events Management | Sports Management",
    "events.description": "Manage events for the sports website",
    "users.title": "User Management | Sports Management",
    "users.description": "Manage system users",
    "settings.title": "Settings | Sports Management",
    "settings.description": "System settings",
    "create.event.title": "Create Event | Sports Management",
    "create.event.description": "Create a new event",
    "edit.event.title": "Edit Event | Sports Management",
    "edit.event.description": "Edit an existing event",
    "create.user.title": "Create User | Sports Management",
    "create.user.description": "Create a new user",

    // Stats
    "total.news": "Total News",
    "upcoming.events": "Upcoming Events",
    "past.events": "Past Events",
    "active.users": "Active Users",
    "from.last.month": "from last month",
    "scheduled.this.week": "scheduled this week",
    "from.last.quarter": "from last quarter",
    "since.last.login": "since last login",
    members: "Members",
    "member.profile": "Member Profile",
    "member.profile.title": "Board Member",
    "other.language": "Other Language",
    "member.not.found": "Member not found",
    "back.to.members": "Back to Members list",
    "confirm.delete.member.title": "Delete member",
    "confirm.delete.member.description": "Are you sure you want to delete this member article?",
    "confirm.delete.member.button": "Delete",
    "confirm.delete.member.cancel": "Cancel",
    "edit.member": "Edit Member",
    "description": "Description",
    "position": "Position",
    "supported.formats":"support formats",
    "drag.or.upload":"Drag or Upload",
"Image":"image",
"name.ar":"name AR ",
"name.en":"name EN ",
"position.ar":"position AR ",
"position.en":"position EN ",
"member.image":"member image ",
"create.member":"create member",
    // Content
    "content.overview": "Content Overview",
    "recent.news": "Recent News",
    "recent.news.description": "Latest news articles published",
    "upcoming.events.title": "Upcoming Events",
    "upcoming.events.description": "Events scheduled for the next 30 days",

    // News
    "add.news": "Add News",
    "create.news": "Create News Article",
    "edit.news": "Edit News Article",
    "news.title.ar": "Title (Arabic)",
    "news.title.en": "Title (English)",
    "news.title.ar.placeholder": "Enter news title in Arabic",
    "news.title.en.placeholder": "Enter news title in English",
    "news.content.ar": "Content (Arabic)",
    "news.content.en": "Content (English)",
    "news.content.ar.placeholder": "Enter news content in Arabic",
    "news.content.en.placeholder": "Enter news content in English",
    content: "Content",
    "publication.date": "Publish Date",
    "select.date": "Select date",
    image: "Image",
    "news.images": "News Images (Max 3 images)",
    "images.added": "Images Added",
    "upload.image": "Upload Image",
    "add.image": "Add Image",
    "choose.image": "Choose Image",
    "change.image": "Change Image",
    "no.image.uploaded": "No image uploaded",
    "image.required": "At least one image is required",
    "update.news": "Update News",
    "update.news.success.title": "News Updated",
    "update.news.success.description": "News article updated successfully.",
    "create.news.success.title": "News Created",
    "create.news.success.description": "News article created successfully.",
    "news.save.error": "Error occurred while saving the news",
    "news.category.placeholder": "Select news category",
    "loading.categories": "Loading categories...",
    "no.categories.available": "No categories available",
    "create.news.button": "Create News Article",
    "news.category": "Category",
    "news.featured": "Featured",
    "news.language": "Language",
    "news.publish": "Publish",
    "news.unpublish": "Unpublish",
    "news.delete": "Delete",
    "news.view": "View",
    "confirm.delete.news.title": "Delete News",
    "confirm.delete.news.description": "Are you sure you want to delete this news article?",
    "confirm.delete.news.button": "Delete",
    "confirm.delete.news.cancel": "Cancel",
    "news.management.title": "News Management",
    "news.delete.success": "News article deleted successfully.",
    "news.delete.error": "Failed to delete news article. Please try again.",
    "open.menu": "Open Menu",
    "edit.news.title": "Edit News | Sports Management",
    "edit.news.description": "Edit an existing news article",
    "news.not.found": "News article not found",
    "news.not.found.error": "News article not found. It may have been deleted or moved.",
"news.per.page":"number of news",

    // Events
    "add.event": "Add Event",
    "create.event": "Create Event",
    "edit.event": "Edit Event",
    "event.title": "Title",
    "event.date": "Event Date",
    "event.time": "Event Time",
    "event.type": "Event Type",
    "event.category": "Category",
    "event.featured": "Featured",
    "event.language": "Language",
    "event.preview": "Preview",
    "event.publish": "Publish",
    "event.unpublish": "Unpublish",
    "event.delete": "Delete",
    "event.view": "View",
    "event.location": "Location",
    location: "Location",
    upcoming: "Upcoming",
    past: "Past",
    "update.event": "Update Event",
    "create.event.button": "Create Event",
    "events.management.title": "Events Management",
    "event.save.draft": "Save as Draft",
    tournament: "Tournament",
    championship: "Championship",
    seminar: "Seminar",
    training: "Training",
    exhibition: "Exhibition",
    conference: "Conference",
    other: "Other",

    // Users
    users: "Users",
    "add.user": "Add User",
    "create.user": "Create User",
    "edit.user": "Edit User",
    name: "Name",
    role: "Role",
    status: "Status",
    admin: "Admin",
    editor: "Editor",
    viewer: "Viewer",
    active: "Active",
    inactive: "Inactive",
    "update.user": "Update User",
    "create.user.button": "Create User",
    "user.management.title": "User Management",
    "user.delete.success.title": "User Deleted",
    "user.delete.success.description": "User has been deleted successfully.",
    "user.delete.error": "Failed to delete user. Please try again.",
    "user.fetch.error": "Failed to fetch user data. Please try again.",
    "users.load.error": "Failed to load users. Please try again later.",
    "user.not.found": "User not found",
    "user.not.found.error": "User not found. It may have been deleted or moved.",
    "phone.number": "Phone Number",
    user: "User",
    "profile.image": "Profile Image",
    "confirm.delete.user.title": "Delete User",
    "confirm.delete.user.description": "Are you sure you want to delete this user?",
    "confirm.delete.user.button": "Delete",
    "confirm.delete.user.cancel": "Cancel",
    
    // Table
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    previous: "Previous",
    next: "Next",
    "no.news.found": "No news articles found.",
    "no.events.found": "No events found.",
    "no.users.found": "No users found.",
    "current.user": "Current User",

    // Profile
    "personal.information": "Personal Information",
    "update.profile": "Update Profile",
    "change.password": "Change Password",
    "current.password": "Current Password",
    "new.password": "New Password",
    "confirm.password": "Confirm Password",
    "profile.picture": "Profile Picture",
    "profile.not.found": "Profile not found",
    "profile.data.error": "Error loading profile data",

    // Settings
    "general.settings": "General Settings",
    language: "Language",
    arabic: "Arabic",
    english: "English",
    notifications: "Notifications",
    "notifications.description": "Manage your notification settings",
    "email.notifications": "Email Notifications",
    "email.notifications.description": "Receive notifications via email when new content is added or updated.",
    "push.notifications": "Push Notifications",
    "push.notifications.description": "Receive instant notifications when new content is added or updated.",

    // Months
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",

    // Footer
    copyright: "© {year} Sports Management. All rights reserved.",
    
    // Platform
    "platform.description": "An integrated platform for efficiently managing sports activities and events",
    "platform.features": "Platform Features",
    "platform.easy.management": "Easy Management",
    "platform.easy.management.description": "User-friendly interface for managing all sports activities and events",
    "platform.secure": "Secure and Reliable",
    "platform.secure.description": "Complete protection for your data and information with advanced encryption",
    "platform.analytics": "Advanced Analytics",
    "platform.analytics.description": "Comprehensive insights and analytics to help you make better decisions",

    // Misc
    by: "By",
    on: "on",
    "pick.a.date": "Pick a date",
    "select.event.type": "Select event type",
    "enter.event.location": "Enter event location",
    "select.option": "Select an option",
    "search.placeholder": "Search...",
    "filter.by": "Filter by",
    "sort.by": "Sort by",
    "items.per.page": "Items per page",
    showing: "Showing",
    of: "of",
    items: "items",
    page: "Page",
    "first.page": "First page",
    "last.page": "Last page",
    "go.to.page": "Go to page",
    "no.results": "No results",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    confirm: "Confirm",
    close: "Close",
    save: "Save",
    add: "Add",
    remove: "Remove",
    view: "View",
    download: "Download",
    upload: "Upload",
    copy: "Copy",
    paste: "Paste",
    cut: "Cut",
    undo: "Undo",
    redo: "Redo",
    "select.all": "Select all",
    "select.none": "Select none",
    select: "Select",
    clear: "Clear",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    refresh: "Refresh",
    more: "More",
    less: "Less",
    "show.more": "Show more",
    "show.less": "Show less",
    expand: "Expand",
    collapse: "Collapse",
    details: "Details",
    summary: "Summary",

    // UI Common
    cancel: "Cancel",
    saving: "Saving...",
    sending: "Sending...",
    "logging.in": "Logging in...",
    required: "Required",
    optional: "Optional",
    preview: "Preview",

    // User form validation errors
    "name.min.length.error": "Name must be at least 3 characters.",
    "email.invalid.error": "Please enter a valid email address.",
    "phone.number.invalid.error": "Please enter a valid phone number.",
    "role.required.error": "Please select a role.",
    "status.required.error": "Please select a status.",
    "password.min.length.error": "Password must be at least 8 characters.",
    "passwords.not.matching.error": "Passwords do not match.",
    
    // News form validation errors
    "title.ar.min.length.error": "Arabic title must be at least 3 characters.",
    "title.en.min.length.error": "English title must be at least 3 characters.",
    "content.ar.min.length.error": "Arabic content must be at least 10 characters.",
    "content.en.min.length.error": "English content must be at least 10 characters.",
    "category.is.required":"please choose news type",

    // Toast notifications
    "please.wait": "Please wait...",
    "operation.success": "Operation completed successfully",
    "operation.failed": "Operation failed",
    "login.success": "Login Successful",
    "welcome.message": "Welcome to the Sport Management Dashboard",
    // "login.failed": "Login Failed",
    // "password.incorrect": "Password is incorrect. Please try again",
    "login.error.message": "An error occurred during login",
    "login.email.not.found": "email not found",
    "image.deleted.success": "Image deleted successfully",
    "your.account.is.not.active": "Your account is not active",
    "login.password.incorrect": "Password is incorrect. Please try again",
    "email.not.found": "Email address is not registered in the system",
    "connection.error": "Connection Error",
    "server.connection.error": "Error connecting to server",
    "saving.settings": "Saving Settings",
    "settings.saved": "Settings Saved",
    "settings.saved.description": "Your dashboard settings have been saved successfully",
    "changing.password": "Changing Password",
    "password.changed": "Password Changed",
    "password.changed.description": "Your password has been changed successfully",
    "resetting.password": "Resetting Password",
    "password.reset.success": "Password Reset",
    "password.reset.error": "Reset Error",
    "password.reset.failed": "Failed to reset password",
    "updating.user": "Updating User",
    "creating.user": "Creating New User",
    "user.updated.title": "User Updated",
    "user.updated.description": "User information has been updated successfully",
    "user.created.title": "User Created",
    "user.created.description": "New user has been created successfully",
    "unauthorized.title": "Unauthorized",
    "unauthorized.description": "You don't have permission to access this page",
    "user.save.error.title": "Error",
    "user.save.error.description": "An error occurred while saving user",
    "event.deleted": "Event Deleted",
    "event.deleted.description": "Event has been deleted successfully",
    "member.deleted": "Member Deleted",
    "member.deleted.description": "Member has been deleted successfully",
    "member.delete.error": "Failed to delete member. Please try again",
    "profile.view.error": "Failed to view profile. Please try again",
    "file.type.invalid": "Invalid file type. Please select an image",
    "file.size.too.large": "File size is too large",
    "file.size.limit.message": "File must not exceed {size}",
    "max.images.limit": "Cannot add more than {0} images",
    "image.delete.error": "Error deleting image",
    "user.delete.error.title": "User Delete Failed",
    "user.delete.error.description": "Failed to delete user. Please try again",

    // Form validations - English
    "verification.code.min.length.error": "Verification code must be at least 6 digits.",
    "current.password.min.length.error": "Current password must be at least 8 characters.",
    "new.password.min.length.error": "New password must be at least 8 characters.",
    "date.required": "Date is required.",
    "time.required": "Time is required.",
    "location.ar.min.length.error": "Arabic location must be at least 5 characters.",
    "location.en.min.length.error": "English location must be at least 5 characters.",
    "category.required": "Please select a category.",
    "unauthorized.error": "You are not authorized to do this process",
    "this.month": "this month",
    "news.increase": "increase in news",
    "news.decrease": "decrease in news",
    "no.change": "no change"
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "ar",
  setLanguage: () => {},
  t: (key: string) => key,
  dir: "rtl",
  isLoaded: false
})

export function useLanguage() {
  return useContext(LanguageContext)
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [isLoaded, setIsLoaded] = useState(false)
  const [language, setLanguage] = useState<Language>("ar")
  const dir = language === "ar" ? "rtl" : "ltr"

  // تنفيذ هذا الأثر عند تحميل المكون لأول مرة فقط
  useEffect(() => {
    try {
      // قراءة تفضيل اللغة من التخزين المحلي
      const savedLanguage = localStorage.getItem("uaemmaf-language") as Language | null
      
      if (savedLanguage && (savedLanguage === "ar" || savedLanguage === "en")) {
        setLanguage(savedLanguage)
      }
      
      // تحديث سمات HTML
      const htmlElement = document.documentElement
      htmlElement.lang = savedLanguage || language
      htmlElement.dir = (savedLanguage === "en") ? "ltr" : "rtl"
    } finally {
      // تعيين الحالة إلى محمّل بغض النظر عن نجاح القراءة من التخزين
      setIsLoaded(true)
    }
  }, [])

  // الاستجابة للتغييرات في اللغة
  useEffect(() => {
    if (!isLoaded) return

    const htmlElement = document.documentElement
    htmlElement.lang = language
    htmlElement.dir = language === "ar" ? "rtl" : "ltr"
  }, [language, isLoaded])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("uaemmaf-language", lang)
  }

  const t = (key: string) => {
    // Type-safe translation lookup
    return (translations[language] as Record<string, string>)[key] || key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir, isLoaded }}>
      {children}
    </LanguageContext.Provider>
  )
}
